// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNrOmS5O3cCUWnqxajk09RHxWo71Zcjqc',
    appId: '1:392508577485:web:1678427220869edeb5fb84',
    messagingSenderId: '392508577485',
    projectId: 'hackson-creo',
    authDomain: 'hackson-creo.firebaseapp.com',
    storageBucket: 'hackson-creo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Zar0M-F4ra1CIQ0RBNjpqAzCsQUDv54',
    appId: '1:392508577485:android:c06e17927573c33eb5fb84',
    messagingSenderId: '392508577485',
    projectId: 'hackson-creo',
    storageBucket: 'hackson-creo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8zjqjfk9xrDczWHIcIan8tS4QFGKQzRs',
    appId: '1:392508577485:ios:6a4953ebeb24ee6fb5fb84',
    messagingSenderId: '392508577485',
    projectId: 'hackson-creo',
    storageBucket: 'hackson-creo.appspot.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8zjqjfk9xrDczWHIcIan8tS4QFGKQzRs',
    appId: '1:392508577485:ios:6a4953ebeb24ee6fb5fb84',
    messagingSenderId: '392508577485',
    projectId: 'hackson-creo',
    storageBucket: 'hackson-creo.appspot.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNrOmS5O3cCUWnqxajk09RHxWo71Zcjqc',
    appId: '1:392508577485:web:caa3a68fe984e9a1b5fb84',
    messagingSenderId: '392508577485',
    projectId: 'hackson-creo',
    authDomain: 'hackson-creo.firebaseapp.com',
    storageBucket: 'hackson-creo.appspot.com',
  );

}